### ISSUE TITLE
tsconfig.json should not necessarily contain files or filesGlob

### ISSUE THREAD

**Issue by dsebastien** [wjohnsto/tsconfig-lint#3]
In my project, I don't use those properties. I only have "exclude", which works fine:
https://github.com/dsebastien/angularjs-webpack-starter/blob/master/tsconfig.json

**Comment by wjohnsto** [comment]
I've been meaning to get to this, thanks for reminding me!

**Comment by wjohnsto** [comment]
A solution for this is in v0.7.0.

**Comment by dsebastien** [comment]
Hi @wjohnsto. 0.7.0 looks better already (finds files), but I need to exclude .d.ts files from the linting process. Is it possible?

**Comment by wjohnsto** [comment]
I thought about this while making the changes. I realize that when using something like [typings/typings](/typings/typings) you can run into issues if you include some of those files (or don't exclude them). This is definitely a problem, unfortunately I don't think it can be solved by simply not linting `.d.ts` files.

In a project that I have I include some self-made `.d.ts` files that I do wish to be linted. In order to make it work with `exclude` I am forced to specifically exclude some of the `.d.ts` files, so my `exclude` resembles the following:

``` json
"exclude": [
    "node_modules",
    "typings/browser",
    "typings/browser.d.ts",
    "typings/main"
]
```

The above will still compile (and include the `typings/main.d.ts`, but all the other typings will be excluded when performing the lint.

**Comment by dsebastien** [comment]
Thanks for your feedback. I'll try this tonight :)
